# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            ![YalcinAktekin](/images/YalcinAktekinLog.png)
tagline:          '[Sources and Bibliographies]'
description:      'Yalcin Aktekin'
url:              https://yalcinaktekin.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
