# Setup
title:            Yalcin Aktekin
tagline:          '{Sources and Bibliographies}'
description:      'Yalcin Aktekin'
url:              https://yalcinaktekin.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:          2.0.0
